name: ai_memo
description: "Your Intelligent Audio Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.8.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  record:
  path_provider:
  file_picker:
  ffmpeg_helper:

  vosk_flutter:
    path: thirdparty/vosk-flutter
  fllama:
    path: thirdparty/fllama
  flutter_riverpod:

  flutterflow_ui:
    path: thirdparty/flutterflow_ui-0.3.1
  flutter_markdown:
  google_fonts:

dev_dependencies:
  flutter_lints:
  lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    #- assets/images/
    #- assets/videos/
    #- assets/audios/
    #- assets/rive_animations/
    #- assets/pdfs/
    #- assets/jsons/
    - assets/models/vosk-model-spk-0.4.zip
    - assets/models/vosk-model-small-en-us-0.15.zip
    - assets/models/vosk-model-small-ja-0.22.zip
