name: ai_memo
description: "Your Intelligent Audio Assistant"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: 3.7.0-267.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  record:
  path_provider:
  file_picker:
  ffmpeg_helper:

  vosk_flutter:
    path: thirdparty/vosk-flutter
  fllama:
    path: thirdparty/fllama
  flutter_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:

  uses-material-design: true

  assets:
    - assets/models/vosk-model-spk-0.4.zip
    - assets/models/vosk-model-small-en-us-0.15.zip
    - assets/models/vosk-model-small-ja-0.22.zip
