name: ai_memo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

platforms:
  android:
  ios:
  macos:
  linux:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: any
  path_provider: ^2.1.3
  system_info2: ^4.0.0
  record: ^5.1.1
  cupertino_icons: ^1.0.8
  whisper_flutter_new:
    path: thirdparty/whisper_flutter_new

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
